# Project name
project:
  name: "Yellow River Basin"
  status: "Ongoing"
  start: 2022
  end: None

# Repository name
repo:
  name: "Water-Allocation-Institution"
  owner: "SongshGeo"
  background: "fig@background"
  license: "MIT"
  introduction: "Institutional shifts and effects to the Yellow River Basins' water uses."

# contributors:
contributors:
  Shuang Song: True
  Huiyu Wen: True
  Shuai Wang: True
  Bojie Fu: True

papers:
  target journal: National Science Review
  current version: v1


# dir structure
structure:
  data:
    source: local
    processed: local
    results: support

  docs:
    papers: 01_manuscript
    docs: support
    drafts: support

  figs:
    diagrams: support
    outputs: support
    resources: support

  tests: support
  notebooks: 01_manuscript
  reports: support

  main:
    modules: 01_manuscript
    tools: 01_manuscript

python:
  version: "<3.8"

links:
  fig@background: "![图片(13)](https://gitee.com/SongshGeo/Picgo2/raw/master/uPic/%E5%9B%BE%E7%89%87%20(13).jpg)"
  github@songshgeo: "[my GitHub](https://github.com/SongshGeo)"
  researchgate@songshgeo: "https://www.researchgate.net/profile/Shuang-Song-14"

log:
  name: "project"
  path: ""
  LOG_FORMAT: "%(asctime)s %(name)s %(levelname)s %(filename)s %(message)s "
  DATE_FORMAT: '%Y-%m-%d  %H:%M:%S %a '
  cmd_level: "WARNING"
  file_level: "INFO"

# Set folder levels to each structure
folder_level:
  # 01_manuscript modules
  mian:
    ignore: False
    doc: True
  # support
  support:
    ignore: False
    doc: False
  # local
  local:
    ignore: True
    doc: False
