
Y_inputs: 'Total water use'

X_inputs: [
    "Province",
    "Year",
    #         'IRR',
    #         'Irrigated area: Total',
    "Irrigated area: Rice",
    "Irrigated area: Wheat",
    "Irrigated area: Maize",
    "Irrigated area: Vegetables and fruits",
    "Irrigated area: Others",
    #         'IND',
    #         'Industrial gross value added (GVA): Total',
    "Industrial gross value added (GVA): Textile",
    "Industrial gross value added (GVA): Papermaking",
    "Industrial gross value added (GVA): Petrochemicals",
    "Industrial gross value added (GVA): Metallurgy",
    "Industrial gross value added (GVA): Mining",
    "Industrial gross value added (GVA): Food",
    "Industrial gross value added (GVA): Cements",
    "Industrial gross value added (GVA): Machinery",
    "Industrial gross value added (GVA): Electronics",
    "Industrial gross value added (GVA): Thermal electrivity",
    "Industrial gross value added (GVA): Others",
    #         'URB',
    "Urban population",
    "Service GVA",
    #         'RUR',
    "Rural population",
    "Livestock population",
    "Total water use",
    #         'area',
    #         'PIRR',
    #         'AIRR',
    "WCI",
    "Ratio of industrial water recycling",
    # #         'Ratio of industrial water evaporated',
    # #         'gdp',
    # #         'gdp-1',
    # #         'gdp-2',
    # #         'gdp-3',
    # #         'gdp-avg',
    "prec",
    "temp",
    #  'wind',
]
